FROM python:3.9.17-bookworm
SHELL ["/bin/bash", "-c"] 

RUN apt update && apt install -y libgeos-dev python3-h5py pkg-config libhdf5-dev

WORKDIR /opt/app

COPY docker/requirements_full.txt requirements.txt

RUN python3 -m venv venv_interpreter && \
    source venv_interpreter/bin/activate && \
	pip3 install wheel && \
    pip3 install -r requirements.txt
